FOCAL_DISTANCE_MAX = 200;
N_SAMPLES_RANDOM = 50;

% good
spread('Com_ery_C_2', ...
        'data/Com_ery_C_2/Result of Substack (1-218)-1.AutoAl_Com_ery_2_1st.tif.zip', ...
        'data/Com_ery_C_2/Result of Substack (1-218)-1_auto_Com_ery_2_2nd.tif.zip', ...
        '', ...
        'data/Com_ery_C_2/Com_ery_C_2_1stimage_inverted_mask_removedtape.png', ...
        'data/Com_ery_C_2/Com_ery_C_2_midrib_filled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_C_3', ...
        'data/Com_ery_C_3/Com_ery_C_3_results_1st (1).tif.zip', ...
        'data/Com_ery_C_3/Results_Com_ery_C_3_2nd.tif.zip', ...
        '', ...
        'data/Com_ery_C_3/Com_ery_C_3_inverted_wbg_taperemoved.png', ...
        'data/Com_ery_C_3/Com_ery_C_3_midrib_filled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
%good
spread('Com_ery_C_4', ...
        'data/Com_ery_C_4/Mask of Com_ery_C_4_1st.tif.zip', ...
        'data/Com_ery_C_4/Mask of Com_ery_C_4_2nd.tif.zip', ...
        'data/Com_ery_C_4/Mask Com_ery_C_4_3rd.tif.zip', ...
        'data/Com_ery_C_4/Com_ery_C_4_inverted_mask_2.png', ...
        'data/Com_ery_C_4/Com_ery_C_4_mask_midribfilled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_L_2', ...
        'data/Com_ery_L_2/Mask of Result of COMERY_L_2_1st (1-219)-1.tif.zip', ...
        'data/Com_ery_L_2/Result of Substack (1-218)-1_Com_ery_L_2_2nd.tif.zip', ...
        '', ...
        'data/Com_ery_L_2/Com_ery_L_2_1stimage_inverted_mask_2.png', ...
        'data/Com_ery_L_2/Com_ery_L_2_mask_midribfilled.png', ...
        3250, ...
        2470, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_L_3', ...
        'data/Com_ery_L_3/Copy of Result_Com_ery_L_3.tif.zip', ...
        '', ...
        '', ...
        'data/Com_ery_L_3/Com_ery_L_3_129_inverted_black leaf_mask.png', ...
        'data/Com_ery_L_3/Com_ery_L_3_mask_midribfilled.png', ...
        2220, ...
        3900, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_L_4', ...
        'data/Com_ery_L_4/Copy of Mask of Com_ery_L_4_1st.tif.zip', ...
        'data/Com_ery_L_4/Copy of Mask of Com_ery_L_4_2nd.tif.zip', ...
        '', ...
        'data/Com_ery_L_4/Com_ery_L_4_inverted_mask_taperemoved.png', ...
        'data/Com_ery_L_4/Com_ery_L_4_mask_midribfilled.png', ...
        2224, ...
        2640, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_M_2', ...
        'data/Com_ery_M_2/Copy of Com_ery_M_2 (1-219)_1st.tif.zip', ...
        'data/Com_ery_M_2/Copy of Com_ery_M_2_2nd_mask.tif.zip', ...
        '', ...
        'data/Com_ery_M_2/Com_ery_M_2_wbg_taperomoved.png', ...
        'data/Com_ery_M_2/Com_ery_M_2_mask_midribfilled.png', ...
        2964, ...
        9336, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_M_3', ...
        'data/Com_ery_M_3/Copy of Mask_Com_ery_M_3.tif.zip', ...
        '', ...
        '', ...
        'data/Com_ery_M_3/Com_ery_M_3_inverted_mask_2.png', ...
        'data/Com_ery_M_3/Com_ery_M_3_mask_midribfilled.png', ...
        3168, ...
        9000, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Com_ery_M_4', ...
        'data/Com_ery_M_4/Copy of Mask ofCom_ery_M_4_1st.tif.zip', ...
        'data/Com_ery_M_4/Copy of Mask_Com_ery_M_4_2nd.tif.zip', ...
        '', ...
        'data/Com_ery_M_4/Com_ery_M_4_inverted_mask_taperemoved.png', ...
        'data/Com_ery_M_4/Com_ery_M_4_mask_midribfilled.png', ...
        3272, ...
        9216, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);




% good
spread('Ace_rub_C_1', ...
        'data/Ace_rub_C_1/Copy of Result of Substack (1-204)-1_Pal_C1.tif.zip', ...
        'data/Ace_rub_C_1/Copy of Result of Substack (1-205)-1_Pal_C1_2.tif.zip', ...
        '', ...
        'data/Ace_rub_C_1/Ace_rub_C_1_mask_whitebg_taperemoved.png', ...
        'data/Ace_rub_C_1/Ace_rub_C_1_mask_midribfilled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_C_2', ...
        'data/Ace_rub_C_2/Copy of Rub_ace_C_2_1st.tif.zip', ...
        'data/Ace_rub_C_2/Copy of Result_Rub_ace_C_2_2nd.tif.zip', ...
        '', ...
        'data/Ace_rub_C_2/Ace_rub_C2_mask_whitebg_taperemoved.png', ...
        'data/Ace_rub_C_2/Ace_C_2_mask_midribfilled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_C_3', ...
        'data/Ace_rub_C_3/Copy of Mask of Result of Substack_Ace_rub_C_3_1st_redo.tif.zip', ...
        'data/Ace_rub_C_3/Copy of Mask of Ace_rub_C_3_2nd.tif.zip', ...
        '', ...
        'data/Ace_rub_C_3/mask_Ace_rub_C_3_wbg_notape.png', ...
        'data/Ace_rub_C_3/Ace_rub_C_3_inverted_crop_CNN_Tile130_factor1_patch200_wholeleaf_3_midrib_filled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_L_1', ...
        'data/Ace_rub_L_1/Copy of Result of Substack (1-207)-1_Pal_L_1_1st.tif.zip', ...
        'data/Ace_rub_L_1/Copy of Result of Substack (1-206)-1_Pal_L_1_2nd.tif.zip', ...
        '', ...
        'data/Ace_rub_L_1/Ace_rub_L_1_mask_wbg_taperemoved.png', ...
        'data/Ace_rub_L_1/Ace_rub_L_1_mask_midribfilled.png', ...
        2570, ...
        2380, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_L_2', ...
        'data/Ace_rub_L_2/Copy of Mask_Rub_ace_L_2_1st.tif.zip', ...
        'data/Ace_rub_L_2/Copy of Mask_Rub_Ace_L_2.tif.zip', ...
        '', ...
        'data/Ace_rub_L_2/Ace_rub_L_2_WB_taperemoved.png', ...
        'data/Ace_rub_L_2/Ace_rub_L_2_mask_midribfilled.png', ...
        2890, ...
        2112, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_L_3', ...
        'data/Ace_rub_L_3/Copy of Mask Rub_ace_L_3_1st.tif.zip', ...
        'data/Ace_rub_L_3/Ace_rub_L_3_2nd_Mask of Result of Substack (1-199)-1_redo_final.tif.zip', ...
        '', ...
        'data/Ace_rub_L_3/Ace_rub_L_3_wbg_taperemoved.png', ...
        'data/Ace_rub_L_3/Ace_rub_L_3_crop_CNN_Tile150_factor1_patch200_3_midrib_filled.png', ...
        1920, ...
        4320, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_M_1', ...
        'data/Ace_rub_M_1/Copy of Substack (1-199)-1_Pal_M_1_1st.tif.zip', ...
        'data/Ace_rub_M_1/Copy of Result of Substack (1-208)_Pal_M_1_2nd-doubled.tif.zip', ...
        '', ...
        'data/Ace_rub_M_1/Ace_rub_M_1_mask_whitebg_taperemoved.png', ...
        'data/Ace_rub_M_1/Ace_rub_M_1_mask_midribfilled.png', ...
        4488, ...
        10728, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);
% good
spread('Ace_rub_M_2', ...
        'data/Ace_rub_M_2/Copy of Mask_Rub_ace_M_2_1st.tif.zip', ...
        'data/Ace_rub_M_2/Copy of Mask of Rub_ace_M_2_2nd.tif.zip', ...
        '', ...
        'data/Ace_rub_M_2/Ace_rub_M_2_mask_WB_taperemoved.png', ...
        'data/Ace_rub_M_2/Ace_rub_M_2_mask_midribfilled.png', ...
        4476, ...
        8724, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);

spread('Ace_rub_M_3', ...
        'data/Ace_rub_M_3/Copy of Mask of Rub_ace_M_3_1st.tif.zip', ...
        'data/Ace_rub_M_3/Copy of Mask of Rub_ace_M_3_2nd.tif.zip', ...
        '', ...
        'data/Ace_rub_M_3/Mask_Ace_rub_M_3_whitebg_taperemoved.png', ...
        'data/Ace_rub_M_3/Ace_rub_M_3_mask_midribfilled.png', ...
        3576, ...
        8148, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);