FOCAL_DISTANCE_MAX = 200;
N_SAMPLES_RANDOM = 50;

spread('Com_ery_L_2', ...
        'data/Com_ery_L_2/Mask of Result of COMERY_L_2_1st (1-219)-1.tif', ...
        'data/Com_ery_L_2/Result of Substack (1-218)-1_Com_ery_L_2_2nd.tif', ...
        'data/Com_ery_L_2/Com_ery_L_2_1stimage_inverted_mask_2.png', ...
        'data/Com_ery_L_2/Com_ery_L_2_mask_midribfilled.png', ...
        3250, ...
        2470, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);

% if there is no second embolism stack, give '' for the stack
spread('Com_ery_L_3', ...
        'data/Com_ery_L_3/Copy of Result_Com_ery_L_3.tif', ...
        '', ...
        'data/Com_ery_L_3/Com_ery_L_3_129_inverted_black leaf_mask.png', ...
        'data/Com_ery_L_3/Com_ery_L_3_mask_midribfilled.png', ...
        2220, ...
        3900, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);

% if there is no second embolism stack, give '' for the stack
spread('Com_ery_M_2', ...
        'data/Com_ery_M_2/Copy of Com_ery_M_2 (1-219)_1st.tif', ...
        'data/Com_ery_M_2/Copy of Com_ery_M_2_2nd_mask.tif', ...
        'data/Com_ery_M_2/Com_ery_M_2_wbg_taperomoved.png', ...
        'data/Com_ery_M_2/Com_ery_M_2_mask_midribfilled.png', ...
        2964, ...
        9336, ...
        155, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);



% for a control leaf
spread('Com_ery_C_2', ...
        'data/Com_ery_C_2/Result of Substack (1-218)-1.AutoAl_Com_ery_2_1st.tif', ...
        'data/Com_ery_C_2/Result of Substack (1-218)-1_auto_Com_ery_2_2nd.tif', ...
        'data/Com_ery_C_2/Com_ery_C_2_1stimage_inverted_mask_removedtape.png', ...
        'data/Com_ery_C_2/Com_ery_C_2_midrib_filled.png', ...
        NaN, ...
        NaN, ...
        NaN, ...
        FOCAL_DISTANCE_MAX, ...
        N_SAMPLES_RANDOM);